# Generated by Django 5.1.3 on 2025-02-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0002_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='название задачи'),
        ),
    ]
